# Generated by Django 5.1.1 on 2024-09-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftpreference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
