# Generated by Django 5.1.1 on 2024-09-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpreference',
            name='confirmed_endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='confirmed_starttime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
