# Generated by Django 5.1.1 on 2024-09-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0002_shiftpreference_confirmed_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftpreference',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftpreference',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
