# Generated by Django 5.1.1 on 2024-09-26 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0002_alter_shiftpreference_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='カラーコードは有効な16進数形式である必要があります（例：#FF0000）', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
