# Generated by Django 5.1.1 on 2024-09-25 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0003_alter_shiftpreference_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('休み', '休み'), ('未定', '未定'), ('学校関連', '学校関連')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shiftgenerator.holiday'),
        ),
    ]
