# Generated by Django 5.1.1 on 2025-05-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0004_remove_holiday_color_alter_shiftpreference_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
