# Generated by Django 5.1.1 on 2025-05-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0005_staff_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSubmissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submission_status', models.CharField(choices=[('初回', '初回'), ('再提出', '再提出'), ('遅刻', '遅刻')], default='初回', max_length=16)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftgenerator.staff')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftgenerator.shiftsubmissionperiod')),
            ],
        ),
    ]
