# Generated by Django 5.1.1 on 2025-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0006_shiftsubmissionperiod_shiftsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftsubmissionperiod',
            name='label',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
