# Generated by Django 5.1.1 on 2025-05-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0007_alter_shiftsubmissionperiod_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftsubmissionperiod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
