# Generated by Django 5.1.1 on 2025-05-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0008_shiftsubmissionperiod_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftsubmissionperiod',
            name='is_default',
        ),
        migrations.AddField(
            model_name='shiftsubmissionperiod',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftsubmissionperiod',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftsubmissionperiod',
            name='type',
            field=models.CharField(choices=[('default', 'デフォルト'), ('temporary', '臨時'), ('HELP', 'ヘルプ')], default='default', max_length=16),
        ),
    ]
