# Generated by Django 5.1.1 on 2025-05-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0009_remove_shiftsubmissionperiod_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftsubmissionperiod',
            name='auto_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
