# Generated by Django 5.1.1 on 2025-06-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0010_shiftsubmissionperiod_auto_close_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftpreference',
            name='description',
        ),
        migrations.AddField(
            model_name='shiftsubmission',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftsubmission',
            name='submission_status',
            field=models.CharField(choices=[('初回', '初回'), ('再提出', '再提出')], default='初回', max_length=16),
        ),
    ]
