# Generated by Django 5.1.1 on 2025-06-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0011_remove_shiftpreference_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRegisterAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register_number', models.IntegerField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_assignments', to='shiftgenerator.shiftpreference')),
            ],
        ),
    ]
