# Generated by Django 5.1.1 on 2025-06-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0012_shiftregisterassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftregisterassignment',
            name='end_offset',
        ),
        migrations.RemoveField(
            model_name='shiftregisterassignment',
            name='start_offset',
        ),
        migrations.AddField(
            model_name='shiftregisterassignment',
            name='register_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftregisterassignment',
            name='register_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
