# Generated by Django 5.1.1 on 2026-01-18 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0013_remove_shiftregisterassignment_end_offset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='excel_code',
            field=models.CharField(blank=True, help_text='Excel列コード（例: a, b, ... , m, n, ...）', max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='excel_code は a〜z（小文字）を 1〜3 文字で入力してください（例: a, m, aa）', regex='^[a-z]{1,3}$')]),
        ),
    ]
