# Generated by Django 5.1.1 on 2026-02-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0014_excelexporttemplate_staff_excel_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shiftsubmission',
            constraint=models.UniqueConstraint(fields=('staff', 'period'), name='uniq_submission_staff_period'),
        ),
    ]
