# Generated by Django 5.1.1 on 2026-02-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0015_shiftsubmission_uniq_submission_staff_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpreference',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='published_endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='published_starttime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
