# Generated by Django 5.1.1 on 2026-02-21 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0016_shiftpreference_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedRegisterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.IntegerField()),
                ('register_start_time', models.TimeField()),
                ('register_end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_register_assignments', to='shiftgenerator.shiftpreference')),
            ],
        ),
    ]
