# Generated by Django 5.1.1 on 2026-02-24 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0017_publishedregisterassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpreference',
            name='published_period',
            field=models.ForeignKey(blank=True, help_text='この確定シフトを公開した募集期間', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_shifts', to='shiftgenerator.shiftsubmissionperiod'),
        ),
    ]
