# Generated by Django 5.1.1 on 2026-03-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0018_shiftpreference_published_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpreference',
            name='submission_period',
            field=models.ForeignKey(blank=True, help_text='このシフトが属する募集期間（編集用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_preferences', to='shiftgenerator.shiftsubmissionperiod'),
        ),
    ]
