# Generated by Django 5.1.1 on 2026-03-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftgenerator', '0019_shiftpreference_submission_period'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shiftsubmissionperiod',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date', 'type'), name='uniq_submission_period_range_type'),
        ),
    ]
